my_file = open('/Users/gennady/PycharmProjects/lesson2/lesson_5/test.txt', 'r')
content = my_file.read()
print(f'Содержимое файла: \n {content}')
my_file = open('test.txt', 'r')
content = my_file.readlines()
print(f'Количество строк в файле - {len(content)}')
my_file = open('test.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print(f'Количество символов {i + 1} - ой строки {len(content[i])-1}') 
my_file = open('test.txt', 'r')
content = my_file.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
my_file.close()